### ISSUE TITLE
Build/Setup Instructions for RR Adblocker

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#12]
Instruction to build and use the extension on various platforms.

Requires creating a Build Instructions.md file for various platforms for testing with concise and to the point instructions along with screenshots to aid to the steps.

**Comment by Rutuj-Runwal** [comment]
@b5i Can you work on this for safari/mac instructions?

**Comment by Rutuj-Runwal** [comment]
@Soham-Mundhada you can also work.on this

**Comment by b5i** [comment]
> @b5i Can you work on this for safari/mac instructions?

Of course! If @Soham-Mundhada want also it is nice too 👍

**Comment by Rutuj-Runwal** [comment]
> > @b5i Can you work on this for safari/mac instructions?
> 
> Of course! If @Soham-Mundhada want also it is nice too 👍

You can start the work no problem.
