### ISSUE TITLE
Support for Firefox Browser

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#17]
The extension was migrated to Manifest V3 in Feb'22 - Mar'22 and we were maintaining a MV2 version for firefox and opera(now opera allows MV3 in it's store) side by side up until May'22.
You can check it out here: https://addons.mozilla.org/en-US/firefox/addon/rr-adblocker/

As firefox has shown slow adoption of MV3 we have decided to port more functinality towards MV2 and maintian it for legacy purposes as a separate branch.
Thus we need you to help create a conversion of this extension for mozilla firefox

### New to the project?
Check out the getting started guide: https://bit.ly/rr-gettingStarted

**Comment by prakrit55** [comment]
Hello there, is this task about upgrading in the manifest.json by Manifest v2?

**Comment by Rutuj-Runwal** [comment]
> Hello there, is this task about upgrading in the manifest.json by Manifest v2? 

The extension is currently in Manifest V3. Firefox doesn't support it currently so need to migrate to Manifest V2. As i mentioned in the note above some APIs need to be changed.
