### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by sanvi0071** [Rutuj-Runwal/RR-Adblocker#22]
### Description

Add favicon in the tab bar

**Comment by Rutuj-Runwal** [comment]
> Taking this one on

Go ahead

**Comment by sanvi0071** [comment]
I wanted to work as a part of hacktoberfest

**Comment by Rutuj-Runwal** [comment]
> I wanted to work as a part of hacktoberfest 

@acenasir already made PR on it so if you want you can check out other issues or create other things
Explore the code there is no rush
