### ISSUE TITLE
💡 Addition of Contribution Page inside options

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#24]
### Description

Integrating a github contributors page inside the options page shown below via a button
The page should have the following:
- Names and images of all the active github contributors with links to their github profiles
- A "Start Contributing" button

You can use the github api to fetch all the active contributors in real time:  
https://api.github.com/repos/Rutuj-Runwal/RR-Adblocker/contributors

![image](https://user-images.githubusercontent.com/59436520/194696044-5bb33028-2873-431b-8db2-43b5776c1dff.png)

### New to the repo?
Check out the getting started guide to help you with the contributions:

https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/Getting_Started.md

**Comment by PaxtonDevs** [comment]
Hello, I'd like to take this issue

**Comment by Rutuj-Runwal** [comment]
> Hello, I'd like to take this issue

Sure

**Comment by PaxtonDevs** [comment]
Contributions has been added

**Comment by Rutuj-Runwal** [comment]
> Contributions has been added

@PaxtonDevs your design is great but you have hard-coded all the contributors into the html which is not ideal.As if a new contributor joins in we have to update the page every time.
What you need to do here is to use the GitHub api(link mentioned in the issue description), it gives a JSON object. You need to loop over it and dynamically insert the contributors with javascript.

**Comment by PaxtonDevs** [comment]
Thank you for the feedback, I will make these changes.

**Comment by Rutuj-Runwal** [comment]
> Thank you for the feedback, I will make these changes. 

Sure👍🏻

**Comment by PaxtonDevs** [comment]
Updates have been added.
