### ISSUE TITLE
💡 Options Page Responsiveness

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#25]
### Description

The options page is not responsive in mobile view. 

Requirements:
- Increase font and area of "Enhancement Options" section to be readable in mobile view
- The "About" section must go under the "Enhancement Options" when viewed on devices with smaller screen sizes
- Should not break the original Desktop view of the page

![image](https://user-images.githubusercontent.com/59436520/194696802-6d1f441a-095e-4b8d-af94-f588bd7f144a.png)

### Screenshots

![image](https://user-images.githubusercontent.com/59436520/194696917-34648ddf-cd30-4084-a7e4-ba573ff555c1.png)

### New to the repo?
Check out the getting started guide to help you with the contributions:

https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/Getting_Started.md

**Comment by Davethadev** [comment]
Hey there. I'd love to contribute. Could you please assign this issue to me

**Comment by Rutuj-Runwal** [comment]
> Hey there. I'd love to contribute. Could you please assign this issue to me

Sure
Have assigned.

**Comment by Davethadev** [comment]
Thanks. Would get started on it now
