### ISSUE TITLE
[DOCS] Improving the README.md file

### ISSUE THREAD

**Issue by saurabhcodes25** [Rutuj-Runwal/RR-Adblocker#26]
### Description

Add contributors list in readme file to make it more extensive/interesting.

### Screenshots
![image](https://user-images.githubusercontent.com/72072373/194701590-fb88eb3e-7c38-43ac-a4a3-ff2c00ecd052.png)

**Comment by Rutuj-Runwal** [comment]
Go ahead

**Comment by saurabhcodes25** [comment]
@Rutuj-Runwal please check #27 and verify.
