### ISSUE TITLE
Alignment in showblocked page

### ISSUE THREAD

**Issue by VarunVerma307** [Rutuj-Runwal/RR-Adblocker#30]
### Description

hey @Rutuj-Runwal 
can I contribute in your project by modifying show blocked page for better user experience??

### Screenshots

![gh](https://user-images.githubusercontent.com/96423892/194719269-49ca3164-8f56-4fba-96b6-f4d4207a9f25.PNG)

**Comment by VarunVerma307** [comment]
please assign this to me!

**Comment by Rutuj-Runwal** [comment]
Hi @VarunVerma307 
Thank you for your interest.
It's not a website it's a browser extension.

Get started with this guide here:

https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md
