### ISSUE TITLE
⚒ Contributors Page Broken

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#33]
### Description

- The contributors page is not working

### Screenshots

![image](https://user-images.githubusercontent.com/59436520/194746494-08e1e5ac-db35-49e5-90e8-e5933be1b9f5.png)

### Browsers

Chrome, Safari, Microsoft Edge

### New to the repo?
Check out the getting started guide to help you with the contributions:

https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md

**Comment by b5i** [comment]
On what page this could be found?
