### ISSUE TITLE
⚒ Extension buttons with different size (height)

### ISSUE THREAD

**Issue by ftonato** [Rutuj-Runwal/RR-Adblocker#35]
### Description

Hello,

I was taking a look at the site and I noticed that the buttons to add the extension to browsers do not follow the same size (height).

The buttons currently have the following heights:

**Chrome:** 58px
**Firefox:** 64px
**Microsoft:** 60px

### Screenshots

<img width="708" alt="CleanShot 2022-10-09 at 10 07 05@2x" src="https://user-images.githubusercontent.com/5417662/194748081-c1d1515d-929c-41f4-a084-9948b3bd02b3.png">

### Browsers

Chrome, Firefox, Brave

**Comment by ftonato** [comment]
I just realised that I opened a ticket for a bug on the site and this is just the repository for the project (extension) itself, so you can close the issue without any problems and sorry for the inconvenience.

**Comment by Rutuj-Runwal** [comment]
> I just realised that I opened a ticket for a bug on the site and this is just the repository for the project (extension) itself, so you can close the issue without any problems and sorry for the inconvenience.

Sure no worries it's a valid issue nonetheless will redirect you to the website repo so you can add it there

It needs a lot more improvements so feel free to make pr's
https://github.com/Rutuj-Runwal/RRAdblocker

**Comment by Rutuj-Runwal** [comment]
While you are here make sure to give this one a star too 🌟
and keep an eye out for more issues here as well
