### ISSUE TITLE
💡Contributors Page Responsiveness

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#36]
### Description

Improve Contributors Page's responsiveness on mobile devices, also remove the unnecessary commas ","

### Screenshots

![image](https://user-images.githubusercontent.com/59436520/194749547-acde04fd-97ff-42ac-95d6-d347516bb5f4.png)

![image](https://user-images.githubusercontent.com/59436520/194749618-aadc539e-bcc5-4241-a8aa-ef78081f563e.png)

**Comment by Aniket1026** [comment]
Can i work on this issue ?

**Comment by Rutuj-Runwal** [comment]
> Can i work on this issue ?

Sure

**Comment by Aniket1026** [comment]
I cannot see the contributors on the website . Where should i look for them?

**Comment by Rutuj-Runwal** [comment]
> I cannot see the contributors on the website . Where should i look for them?
This is not a typical website it's a browser extension so things will be a bit different
Check out the getting started guide here:
https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md

**Comment by efs0-cod3** [comment]
I possible assign me

**Comment by Rutuj-Runwal** [comment]
> I possible assign me

Yes sure you can work on this too
Make the UI better

**Comment by efs0-cod3** [comment]
let me know what you think!
<img src='https://res.cloudinary.com/effe0/image/upload/v1665312209/Screen_Shot_2022-10-09_at_6.41.59_AM_igalnf.png'>

**Comment by Rutuj-Runwal** [comment]
> let me know what you think!
> <img src='https://res.cloudinary.com/effe0/image/upload/v1665312209/Screen_Shot_2022-10-09_at_6.41.59_AM_igalnf.png'>

Looks good enough though can you keep the background color white itself?

**Comment by efs0-cod3** [comment]
sure no problem

**Comment by rajSaheel** [comment]
Please close this issue

**Comment by Rutuj-Runwal** [comment]
> Please close this issue
> 

Thanks for informing
