### ISSUE TITLE
💡 Animation

### ISSUE THREAD

**Issue by Eknoor02** [Rutuj-Runwal/RR-Adblocker#38]
### Description

Adding the animation on the text, objects of the section

**Comment by Rutuj-Runwal** [comment]
Can you be a bit more specific about what type of animations and where exactly you want to add them?

**Comment by Eknoor02** [comment]
Adding the animation on scroll with the aos classes 
On the text and images of the MORE THAN ADBLOCK section

**Comment by Rutuj-Runwal** [comment]
Thank you for your interest but this repository is for the core extension not the website.
Kindly check the readme carefully before making an issue 
The website repo is here: https://github.com/Rutuj-Runwal/RRAdblocker

You can open the issue there

**Comment by Rutuj-Runwal** [comment]
> Thank you for your interest but this repository is for the core extension not the website. Kindly check the readme carefully before making an issue The website repo is here: https://github.com/Rutuj-Runwal/RRAdblocker
> 
> You can open the issue there

@Eknoor02 You can check out the website repo and contribute there 
Thank you for showing interest in RR-Adblocker
