### ISSUE TITLE
UI ENHANCEMENT

### ISSUE THREAD

**Issue by kushaljgec2025** [Rutuj-Runwal/RR-Adblocker#39]
### Description

UI ENHANCEMENT
i want to enhance the  UI with CSS

I like to contribute to this project. please assign me

**Comment by Rutuj-Runwal** [comment]
Mention the specific
What exactly will you use the css for?
What enhancements in the UI will be made?

Attach screenshots of where the improvement will be made.

**Comment by kushaljgec2025** [comment]
I will add some hover effects and can add appropriate color combinations.

**Comment by Rutuj-Runwal** [comment]
Sure you can go ahead

Also if you want to contribute to other projects here is the repo for this extension's website: https://github.com/Rutuj-Runwal/RRAdblocker
