### ISSUE TITLE
Website: Light / Dark Mode Toggle Button

### ISSUE THREAD

**Issue by lordashuchauhan** [Rutuj-Runwal/RR-Adblocker#40]
### Description

Adding a toggle button that switches between light and dark mode,
@Rutuj-Runwal kindly assign me this under HacktoberFest 2022.

**Comment by Rutuj-Runwal** [comment]
Do you want to add toggle to the extension or to the website??

**Comment by lordashuchauhan** [comment]
To the website.

**Comment by Rutuj-Runwal** [comment]
> To the website.

This is the repo for the actual extension.
You can open an issue here for the website: https://github.com/Rutuj-Runwal/RRAdblocker

The extension's option page also needs a dark mode toggle though so you can also see the getting started guide and work on it as well if you like: https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md

**Comment by Rutuj-Runwal** [comment]
> > To the website.
> 
> This is the repo for the actual extension. You can open an issue here for the website: https://github.com/Rutuj-Runwal/RRAdblocker
> 
> The extension's option page also needs a dark mode toggle though so you can also see the getting started guide and work on it as well if you like: https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md

@lordashuchauhan  You can check out the website repo and contribute there 
Thank you for showing interest in RR-Adblocker
