### ISSUE TITLE
Dark mode button and collapsed navbar position

### ISSUE THREAD

**Issue by Aniket1026** [Rutuj-Runwal/RR-Adblocker#55]
### Description

The dark mode button and the collapsed navbar . Their position is slightly wrong . Problem includes
* Not able to tap the exact button.
* Both are positioned one over another.
* Makes the user experience bad.

Improvements : 
* Positioning them separately.
* Improve user experience on small device.

Assign me so I can make improvements 😄

### Screenshots

<img width="498" alt="adBlocker hacktoberfest" src="https://user-images.githubusercontent.com/92184189/195179311-ab38c4e9-1a00-4e33-aba2-d8a33a6072dc.PNG">

**Comment by Rutuj-Runwal** [comment]
Thanks for your interest.
This is the extension's actual source code.
This issue is related to the website you can create it here: 
 https://github.com/Rutuj-Runwal/RRAdblocker/

**Comment by Rutuj-Runwal** [comment]
> Thanks for your interest. This repository contains the extension's actual source code. This issue is related to the website which has it's own separate repository you can create the issue in its repository : https://github.com/Rutuj-Runwal/RRAdblocker/

@Aniket1026 kindly create the issue in the website repo

**Comment by Aniket1026** [comment]
> > Thanks for your interest. This repository contains the extension's actual source code. This issue is related to the website which has it's own separate repository you can create the issue in its repository : https://github.com/Rutuj-Runwal/RRAdblocker/
> 
> @Aniket1026 kindly create the issue in the website repo

Done , created the issue on the other repo 😄.
