### ISSUE TITLE
⚒ Popup UI not taking full screen in Mobile View

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Rutuj-Runwal/RR-Adblocker#60]
### Description

The popup of the extension is not taking the full screen in Mobile browsers that support extension.

This responsiveness bug is on mobile only. Adding some mediaqyeries should fix the issue

### New to the project?
Check out the getting started guide: https://bit.ly/rr-gettingStarted

### Screenshots

Popup not displayed properly in mobile view.

![Popup issue in mobile view](https://user-images.githubusercontent.com/59436520/195518663-91685a1e-3fd6-41d0-a91c-ea6b5518c9c4.jpg)

**Comment by Jozefik** [comment]
Hello, is this issue free ? I can work on it.

**Comment by Rutuj-Runwal** [comment]
> Hello, is this issue free ? I can work on it.

Yes sure
Don't forget to go through the getting started guide

**Comment by Jozefik** [comment]
Is this how you wanted it ? 

![image](https://user-images.githubusercontent.com/1617822/195661483-eeaf8cda-2e1d-4bd6-a7f4-b6a6588c7513.png)

**Comment by Rutuj-Runwal** [comment]
> Is this how you wanted it ? 
> 
> ![image](https://user-images.githubusercontent.com/1617822/195661483-eeaf8cda-2e1d-4bd6-a7f4-b6a6588c7513.png)
> 

Yes that is exactly it.
Amazing job
May I know how you imported your own compiled version into the mobile browser?

**Comment by Jozefik** [comment]
Okay, i will make PR.

I'm using Visual Studio Code with plugin called Live Server. You just open .html page with that and when you are on same network with mobile phone, you have to open IP of computer with port (5500) and you can see live preview of code.

**Comment by Rutuj-Runwal** [comment]
> Okay, i will make PR.
> 
> I'm using Visual Studio Code with plugin called Live Server. You just open .html page with that and when you are on same network with mobile phone, you have to open IP of computer with port (5500) and you can see live preview of code.

Thanks for the info
Sure waiting for your PR
