### ISSUE TITLE
⚒ Incorrect grammar

### ISSUE THREAD

**Issue by immattdavison** [Rutuj-Runwal/RR-Adblocker#64]
### Description

The options page has some grammatical errors. These are particularly prominent in the tooltips.

### Browsers

Chrome, Firefox, Safari, Microsoft Edge, Brave, Kiwi (Android)

**Comment by Rutuj-Runwal** [comment]
Hello @immattdavison 
Welcome to the project 
Glad to have you here!

Sure you can correct the errors
I can assign if you like

**Comment by immattdavison** [comment]
I already opened the PR @Rutuj-Runwal
