### ISSUE TITLE
Constant Reassignment Error

### ISSUE THREAD

**Issue by swarajp486** [Rutuj-Runwal/RR-Adblocker#8]
In `background.js`, the code at line number `88`makes the  if statement immediately following it unsuable.
As the `urlData` variable is declared as constant, it cannot be updated inside the if statement which will throw an error and abort the service worker when the if statement holds true and the statement is reached.

``` 
const urlData = text.split("\n");
if(urlData.length>=4950){
     urlData = urlData.slice(0,4949);
 }
```

**Comment by Rutuj-Runwal** [comment]
Thanks for pointing it out. This is a very big error as it makes the whole code vulnerable to constant reassignment.
Great work. You can proceed with a fix.

**Comment by swarajp486** [comment]
> Thanks for pointing it out. This is a very big error as it makes the whole code vulnerable to constant reassignment. Great work. You can proceed with a fix.

Yes sure.
